# Generated by Django 5.0.7 on 2024-07-28 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photh')),
                ('n_of_subscribers', models.DecimalField(decimal_places=0, max_digits=100, verbose_name='Number of subscribers(VK)')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2, null=0, verbose_name='Seller rating')),
            ],
        ),
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type_of_clothing', models.CharField(max_length=255, verbose_name='Name')),
                ('content', models.TextField(blank=True, verbose_name='Description')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photh')),
                ('rating', models.DecimalField(decimal_places=0, max_digits=2, null=0, verbose_name='Rating')),
                ('cost', models.DecimalField(decimal_places=0, max_digits=10, null=0, verbose_name='Cost of Clothing')),
            ],
        ),
        migrations.DeleteModel(
            name='Vetements',
        ),
    ]
