# Generated by Django 5.0.7 on 2024-07-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0002_brent_cloth_delete_vetements'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='sold',
            field=models.BooleanField(default=False, verbose_name='Sold cloth or not'),
        ),
    ]
