# Generated by Django 5.0.7 on 2024-07-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0003_cloth_sold'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brent',
            new_name='Brend',
        ),
    ]
