# Generated by Django 5.0.7 on 2024-07-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0004_rename_brent_brend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
