# Generated by Django 5.0.7 on 2024-07-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0005_alter_brend_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brend',
            name='n_of_subscribers',
            field=models.DecimalField(decimal_places=1, max_digits=100, verbose_name='Number of subscribers(VK)'),
        ),
        migrations.AlterField(
            model_name='brend',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=0, verbose_name='Seller rating'),
        ),
    ]
