# Generated by Django 5.0.7 on 2024-07-28 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0008_alter_brend_rating'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brend',
            new_name='Brand',
        ),
    ]
