# Generated by Django 5.0.7 on 2024-07-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0009_rename_brend_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(upload_to='media/photos/', verbose_name='Photo'),
        ),
    ]
