# Generated by Django 5.0.7 on 2024-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0010_alter_cloth_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(upload_to='media/photos/', verbose_name='Photo'),
        ),
    ]
