# Generated by Django 5.0.7 on 2024-07-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0011_alter_brand_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='photo',
            field=models.ImageField(upload_to='media/Brands/', verbose_name='Photo'),
        ),
    ]
