# Generated by Django 5.0.7 on 2024-07-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0014_alter_cloth_photo_alter_cloth_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='sold',
        ),
        migrations.AddField(
            model_name='cloth',
            name='limited',
            field=models.BooleanField(default=False, verbose_name='Limited edition?'),
        ),
    ]
