# Generated by Django 5.0.7 on 2024-08-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0015_remove_cloth_sold_cloth_limited'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='brand',
            field=models.CharField(default='', max_length=255, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='cost',
            field=models.DecimalField(decimal_places=0, default='', max_digits=10, null=0, verbose_name='Cost of Clothing'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(default='', upload_to='media/Clothes/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='rating',
            field=models.DecimalField(decimal_places=0, default='', max_digits=2, null=0, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='type_of_clothing',
            field=models.CharField(default='', max_length=255, verbose_name='Type of clothing'),
        ),
    ]
