# Generated by Django 4.2.16 on 2024-10-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0020_alter_cloth_count_of_votes_alter_vote_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='count_of_votes',
            field=models.IntegerField(default='1'),
        ),
    ]
