# Generated by Django 4.2.16 on 2024-10-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0022_alter_cloth_count_of_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='rating',
            field=models.FloatField(default='', max_length=2, null=0, verbose_name='Rating'),
        ),
    ]
