# Generated by Django 4.2.16 on 2024-10-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0023_alter_cloth_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vote',
            old_name='rating',
            new_name='old_rating',
        ),
    ]
