# Generated by Django 4.2.16 on 2024-10-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0024_rename_rating_vote_old_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='photo2',
            field=models.ImageField(default='', upload_to='media/Clothes/', verbose_name='Photo2'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='photo3',
            field=models.ImageField(default='', upload_to='media/Clothes/', verbose_name='Photo3'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='photo',
            field=models.ImageField(default='', upload_to='media/Clothes/', verbose_name='Photo1'),
        ),
    ]
