# Generated by Django 4.2.16 on 2024-10-19 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clothes', '0025_cloth_photo2_cloth_photo3_alter_cloth_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='photo2',
            field=models.ImageField(blank=True, default='', upload_to='media/Clothes/', verbose_name='Photo2'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='photo3',
            field=models.ImageField(blank=True, default='', upload_to='media/Clothes/', verbose_name='Photo3'),
        ),
    ]
